export default {
    USER_LOGIN: "USER_LOGIN",
    GET_PRODUCT_LISTS : "GET_PRODUCT_LISTS",
    ADD_TO_CART : "ADD_TO_CART",
    GET_FILTER_PRODUCTS : "GET_FILTER_PRODUCTS",
    GET_FILTER_SEARCH : "GET_FILTER_SEARCH",
    GET_FILTER_BY_BRAND : "GET_FILTER_BY_BRAND",
    GET_FILTER_BY_PRICE : "GET_FILTER_BY_PRICE"
}